build:
	cd implementations/electronApp && npm install && npm run build

test:
	cd implementations/electronApp && npm run test

run:
	cd implementations/electronApp && npm run electron:dev

package-linux:
	cd implementations/electronApp && npm run electron:build -- --linux

package-win:
	cd implementations/electronApp && npm run electron:build -- --win

package-mac:
	cd implementations/electronApp && npm run electron:build -- --mac
